### ISSUE TITLE
Undefined index: output_ResponseCode 

### ISSUE THREAD

**Issue by punisher-n** [alphaolomi/laravel-pesa-demo#3]
I'm trying to run this demo but got an Exception that says Undefined index: output_ResponseCode @alphaolomi

**Comment by alphaolomi** [comment]
Hello @punisher-n 

i have run the code again it seem to work on php 7.1 and 8 too 

i would like to mention that the Undefined index:output_ResponseCode is a result of an exception that is not handled

1. Ensure you have connect credentials 
 this is for example of sandbox environment
correct Public Key for sandbox env
valid API key with enabled services

Other provide steps to reproduce you scenario

**Comment by alphaolomi** [comment]
Hello @punisher-n any progress ?
